name: Deploy to EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy via SSH
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Deploy to EC2 server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            source ~/.bashrc
            source ~/.nvm/nvm.sh
            cd /home/ubuntu/.ssh/bayut-monitor
            git pull origin main
            npm install
            pm2 reload ecosystem.config.cjs
